ci(test): 更新 logs-analyse 的测试

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -162,23 +162,22 @@ jobs:
       - name: 测试 - logs-analyse
         shell: bash
         run: |-
-          if [[ "${{ runner.os }}" == "Windows" ]]; then
-            ARG="y"
-          else
-            ARG="n"
+          echo "[DEBUG] 运行 python ./Release/src/sundry.py logs-analyse 422513 --no-keep-logs"
+          python ./Release/src/sundry.py logs-analyse 422513 --no-keep-logs || exit_code=$?
+          if [ "${exit_code:-0}" -nq 1 ]; then
+            echo "[ERROR] logs-analyse 预期返回退出代码 1，实际为 ${exit_code:-0}"
+            exit 1
           fi
 
-          echo "========== Validation-Installation-Error =========="
-          echo "[DEBUG] 运行 python ./Release/src/sundry.py logs-analyse \"https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=244050\" $ARG y"
-          python ./Release/src/sundry.py logs-analyse "https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=244050" $ARG y
+          echo "[DEBUG] 运行 python ./Release/src/sundry.py cleanup logs-analyse"
+          python ./Release/src/sundry.py cleanup logs-analyse
 
-          echo "=========== Validation-Executable-Error ==========="
-          echo "[DEBUG] 运行 python ./Release/src/sundry.py logs-analyse \"https://github.com/microsoft/winget-pkgs/pull/323579\" $ARG n"
-          python ./Release/src/sundry.py logs-analyse "https://github.com/microsoft/winget-pkgs/pull/323579" $ARG n
-
-          echo "===================== Cleanup ====================="
-          echo "[DEBUG] 运行 python ./Release/src/sundry.py logs-analyse cleanup"
-          python ./Release/src/sundry.py logs-analyse cleanup
+          echo "[DEBUG] 运行 python ./Release/src/sundry.py logs-analyse 422513 --dateiled --no-keep-logs"
+          python ./Release/src/sundry.py logs-analyse 422513 y --dateiled --no-keep-logs || exit_code=$?
+          if [ "${exit_code:-0}" -nq 1 ]; then
+            echo "[ERROR] logs-analyse 预期返回退出代码 1，实际为 ${exit_code:-0}"
+            exit 1
+          fi
 
       - name: 测试 - verify
         shell: bash
@@ -396,7 +395,6 @@ jobs:
 
           echo "[DEBUG] 运行 python ./Release/src/sundry.py cleanup logs-analyse"
           python ./Release/src/sundry.py cleanup logs-analyse
-          # logs-analyse cleanup 前面测试过了，一样的
           ls -a -R /tmp/Sundry
 
           echo "[DEBUG] 运行 python ./Release/src/sundry.py cleanup autoremove"
@@ -441,7 +439,6 @@ jobs:
 
           echo "[DEBUG] 运行 python ./Release/src/sundry.py cleanup logs-analyse"
           python ./Release/src/sundry.py cleanup logs-analyse
-          # logs-analyse cleanup 前面测试过了，一样的
           tree -a -f /tmp/Sundry/
 
           echo "[DEBUG] 运行 python ./Release/src/sundry.py cleanup autoremove"
